const listPublicEventsSchema = {
    title:'response from get list of public events schema',
    type:'object',
    required:['body', 'status', 'headers'],
    properties:{
        status:{
            type: 'number'
        },
        body:{
            type:'array',
            items:{
                type:'object',
                required:['id','type','actor','repo','payload','public','created_at'],
                properties:{
                    org:{
                        type:'object'
                    },
                    id:{
                        type:'string'
                    },
                    type:{
                        type:'string'
                    },
                    actor:{
                        type:'object',
                        required:['id','login','display_login','gravatar_id','url','avatar_url'],
                        properties:{
                            id:{
                                type:'number',
                            },
                            login:{
                                type:'string'
                            },
                            display_login:{
                                type:'string'
                            },
                            gravatar_id:{
                                type:'string'
                            },
                            url:{
                                type:'string'
                            },
                            avatar_url:{
                                type:'string'
                            }
                        },

                    },
                    repo:{
                        type:'object',
                        required:['id','name','url'],
                        properties:{
                            id:{
                                type:'number'
                            },
                            name:{
                                type:'string'
                            },
                            url:{
                                type:'string'
                            }
                        }
                    },
                    payload:{
                        type:'object',
                        properties:{
                            push_id:{
                                type:'number'
                            },
                            size:{
                                type:'number'
                            },
                            distinct_size:{
                                type:'number'
                            },
                            ref:{
                                type:['string','null']
                            },
                            head:{
                                type:'string'
                            },
                            before:{
                                type:'string'
                            },
                            commits:{
                                type:'array',
                                items:{
                                    type:'object',
                                    properties:{
                                        sha:{
                                            type:'string'
                                        },
                                        author:{
                                            type:'object',
                                            properties:{
                                                email:{
                                                    type:'string'
                                                },
                                                name:{
                                                    type:'string'
                                                }
                                            }
                                        },
                                        message:{
                                            type:'string'
                                        },
                                        distinct:{
                                            type:'boolean'
                                        },
                                        url:{
                                            type:'string'
                                        }
                                    }
                                }
                            },
                            ref_type:{
                                type:'string'
                            },
                            master_branch:{
                                type:'string'
                            },
                            description:{
                                type:['null','string']
                            },
                            pusher_type:{
                                type:'string'
                            },
                            action:{
                                type:'string'
                            },
                            issue:{
                                type:'object'
                            },
                            comment:{
                                type:'object'
                            },
                            number:{
                                type:'number'
                            },
                            pull_request:{
                                type:'object'
                            }
                        }
                    },
                    public:{
                        type:'boolean'
                    },
                    created_at:{
                        type:'string'
                    }
                }
            }
        },
        headers:{
            type:'object'
        }
    }
};

exports.listPublicEventsSchema = listPublicEventsSchema;